Public/css/style.css
Resources/Views/Home/_speakers.leaf

This PR adds the organisation for each speaker to the website

Adding organisation to the speakers profile on the website

---

Resources/Views/Home/_speakers.leaf

A small tweak, just hides the twitter if they don't have one. We could look to expand this in future by allowing different socials, but this is a good start.
| Preview |
| - | 
|<img width="1381" alt="Screenshot 2022-06-14 at 22 27 54" src="https://user-images.githubusercontent.com/13989549/173692247-e61913bf-ad94-47cf-a3bc-a25580076291.png">|

Hide the twitter icon if a speaker doesn't have one

---

Sources/App/routes.swift

This is increasingly important because otherwise it queries based on the last update, so if we have to make schedule changes it will change the ordering.

Sorting the DB Query Based on Start Time

---

Sources/App/Features/Activities/Controllers/ActivityAPIController.swift
Sources/App/Features/Speakers/Controllers/SpeakerController.swift

The S3 requests should be waited on - I believe this is meaning images will fail if they're large as they get cut off before they can finish

Wait for requests to S3

---

Sources/App/Features/Activities/Models/ActivityResponse.swift
Sources/App/Features/Activities/Transformers/ActivityTransformer.swift
Sources/App/Features/Events/Models/Event.swift
Sources/App/Features/Presentations/Models/PresentationResponse.swift
Sources/App/Features/Presentations/Transformers/PresentationTransformer.swift
Sources/App/Features/Schedule/ScheduleAPIController.swift
Sources/App/Features/Slots/Models/SlotResponse.swift
Sources/App/Features/Slots/Transformers/SlotTransformer.swift
Sources/App/Features/Speakers/Models/SpeakerResponse.swift
Sources/App/Features/Speakers/Transformers/SpeakerTransformer.swift
Sources/App/Features/Utilities/GenericResponse.swift
Sources/App/Features/Utilities/Transformer.swift
Sources/App/routes.swift

Adds the first endpoint, including a system for transforming data and returning it to the clients.
Basic concept is just to map content rather than returning raw stuff from the database. The only transformer I didn't build was sponsors as I think someone else is about to do that 🚀 
As this is not directly requesting slots, it lives inside its own /schedule endpoint.
```json
{
"data": [
{
"startTime": "2000-01-01T08:00:00Z",
"id": "D41101AB-445E-483A-B7F0-552E8CB3537E",
"activity": {
"image": "-6A73A5E2-3B09-4665-88F0-5F4522377F8F",
"id": "DB5DA71B-F0DD-4040-BD2A-323FB06556FF",
"title": "snacks",
"subtitle": "snaaaaaaaacks",
"description": "snaaaaaaaak",
"metadataURL": ""
},
"duration": 30
},
{
"startTime": "2000-01-01T09:40:00Z",
"id": "448A53B8-F199-42EF-8ABF-0CDF74A47427", …
```

Schedule API

---

Sources/App/Features/Activities/Models/ActivityResponse.swift
Sources/App/Features/Activities/Transformers/ActivityTransformer.swift
Sources/App/Features/Events/Models/EventResponse.swift
Sources/App/Features/Events/Transformer/EventTransformer.swift
Sources/App/Features/Presentations/Models/PresentationResponse.swift
Sources/App/Features/Presentations/Transformers/PresentationTransformer.swift
Sources/App/Features/Schedule/Models/ScheduleResponse.swift
Sources/App/Features/Schedule/ScheduleAPIController.swift
Sources/App/Features/Schedule/Transformer/ScheduleTransformer.swift
Sources/App/Features/Slots/Models/SlotResponse.swift
Sources/App/Features/Slots/Transformers/SlotTransformer.swift

We pulled the timestamps out, turned them into dates, then they got encoded again. This way, we just trust the string we get out.
I merged in the work for events as its another fix for this same endpoint, and it makes sense to just have one client side change for this instead of trying to do two separate refactors for the same thing.
```
{
"data": {
"event": {
"id": "4F00C6AF-93D0-4E31-BA8F-7ECD5CC0BBDB",
"name": "Ayyy",
"location": "Ayyyy",
"date": "30-08-2022"
},
"slots": [
{
"startTime": "09:00",
"id": "AC4D4B63-50C2-4D42-BEB4-D7299F9C199B",
"presentation": {
"speaker": {
"profileImage": "-8750EE04-19C0-4475-AC84-2FB9611D1383",
"twitter": "a",
"id": "4B8A4CCB-3B2F-4049-935E-47A243ECA513",
"presentations": [],
"biography": "a",
"organisation": "a",
"name": "a"
},
"id": …
```

Return the event with the schedule

---

Resources/Views/Authentication/activity_form.leaf
Sources/App/Features/Activities/Controllers/ActivityAPIController.swift

The sponsor code shows a nice preview, and handles when you edit without adding a new image. I've cloned that approach ( thanks for the code @adamoxley! I just copied it over 😄 ).
| Example |
| - | 
|<img width="1037" alt="Screenshot 2022-08-02 at 00 32 14" src="https://user-images.githubusercontent.com/13989549/182262314-a62e59b5-fcad-4be8-b5f7-e186709c88bc.png">|

Refactor image uploads on activites to match Sponsors

---

Sources/App/Features/Activities/Transformers/ActivityTransformer.swift
Sources/App/Features/Speakers/Transformers/SpeakerTransformer.swift
Sources/App/Features/Utilities/ImageTransformer.swift

The client had to hard code a URL for the storage buckets which is less than ideal. This change makes sure that images all go through a transformer which adds the bucket to it.

Transform image URLS

---

Sources/App/Features/Activities/Controllers/ActivityAPIController.swift
Sources/App/Features/Local/LocalAPIController.swift
Sources/App/Features/Location Categories/Migrations/LocationCategory+Migration+V1.swift
Sources/App/Features/Location Categories/Model/LocationCategory.swift
Sources/App/Features/Location Categories/Model/LocationCategoryResponse.swift
Sources/App/Features/Location Categories/Transformers/LocationCategoryTransformer.swift
Sources/App/Features/Locations/Migrations/Location+Migration+V1.swift
Sources/App/Features/Locations/Model/Location.swift
Sources/App/Features/Locations/Model/LocationResponse.swift
Sources/App/Features/Locations/Transformers/LocationTransformer.swift
Sources/App/Features/Schema.swift
Sources/App/Migrations.swift
Sources/App/routes.swift

Adds the data for the local endpoint. It doesn't add a CMS for it, but given this is unlikely to change im ok with that one personally 😄 
Should unblock local page being worked on 🙏🏻
Sample response:
```swift
{
"data": [
{
"symbolName": "wineglass.fill",
"id": "BD99AE67-B891-4EF0-B22A-81F89926555B",
"name": "Wine",
"locations": [
{
"id": "BD99AE67-B891-4EF0-B22A-81F89926555B",
"lat": 53.796072000000002,
"long": -1.544208,
"name": "Alchemist",
"url": "https://thealchemist.uk.com/venues/leeds-trinity/"
}
]
}
]
}
```
Really simple response, just enough to show litle pins with URLs. Allows for design freedom too as you can re-use the category symbols.

Add local endpoint & entities

---

Public/css/style.css
Resources/Views/Admin/presentations.leaf
Resources/Views/Authentication/presentation_form.leaf
Resources/Views/Home/_schedule.leaf
Sources/App/Features/Local/LocalAPIController.swift
Sources/App/Features/Presentations/Controllers/PresentationAPIController.swift
Sources/App/Features/Presentations/Controllers/PresentationViewController.swift
Sources/App/Features/Presentations/Models/Migrations/Presentation+Migration+V2.swift
Sources/App/Features/Presentations/Models/Presentation.swift
Sources/App/Features/Presentations/Models/PresentationResponse+V2.swift
Sources/App/Features/Presentations/Transformers/PresentationTransformerV2.swift
Sources/App/Features/Schedule/Models/ScheduleResponse+V2.swift
Sources/App/Features/Schedule/ScheduleAPIController+V2.swift
Sources/App/Features/Schedule/Transformer/ScheduleTransformer+V2.swift
Sources/App/Features/Slots/Models/SlotResponse+V2.swift
Sources/App/Features/Slots/Transformers/SlotTransformer+V2.swift
Sources/App/Migrations.swift
Sources/App/routes.swift

Adds the basic work needed to support a second speaker. I've done it this way to achive the desired effect without any complex migrations or huge changes, allowing for a pending launch to not be delayed.
- Adds the second speaker to the presentation model
- Adds a toggle to enable a second speaker on the presentation form
- Adds UI for a second speaker on the scheudle ( just splits the image space )
- Adds a v2 endpoint so you can now get multiple speakers
I could not work out a way to stop you selecting the same thing twice.
-- 
visuals
Images will work on the site :)
| Form/Admin | 
| - | 
|<img width="1038" alt="Screenshot 2022-08-18 at 17 28 13" src="https://user-images.githubusercontent.com/13989549/185447900-5148ef4b-8d60-4baa-96df-a88e07f5b42b.png">
| Schedule |
| - | 
|<img …

Add the option to configure a second speaker

---

Sources/App/routes.swift

A mistake was made using v2 for the API use for retrieving the schedule.  As the app is still in development there is no reason to move to v2.

Fix wrong schedule api version

---

Procfile
Resources/Views/Authentication/presentation_form.leaf
Resources/Views/Authentication/slot_form.leaf
Sources/App/Features/Presentations/Controllers/PresentationAPIController.swift
Sources/App/Features/Presentations/Models/Migrations/Presentation+Migration+V3.swift
Sources/App/Features/Presentations/Models/Presentation.swift
Sources/App/Features/Presentations/Models/PresentationResponse+V2.swift
Sources/App/Features/Presentations/Models/PresentationResponse.swift
Sources/App/Features/Presentations/Transformers/PresentationTransformer.swift
Sources/App/Features/Presentations/Transformers/PresentationTransformerV2.swift
Sources/App/Migrations.swift

Adds a new optional Slide URL entry for a Presentation and passes this back if it exists to the schedule API response.  
Also added `release: Run migrate -y` to the `Procfile` to allow migrations to happen when releasing.

Add Slido URL option to a Presentation

---

Sources/App/Features/Push/Controllers/PushController.swift
Sources/App/Features/Push/Migrations/PushMigration.swift
Sources/App/Features/Push/Migrations/PushMigrationV2.swift
Sources/App/Features/Push/Models/Token.swift
Sources/App/Features/Schema.swift
Sources/App/Migrations.swift

Adds logic to update existing tokens (now with updated date) as well as handling new registrations.  
Migrations moved to correct location to allow auto migrate to work as expected.

Correctly handle Push registration for existing tokens

---

Sources/App/Migrations.swift

This was recently removed in order to remove the need for TLS checking in local environments, this was done under the documentation provided by Postgres NIO which specifies that the client TLS configuration is defined automatically when the connection string (which comes from the DATABASE_URL environment variable) contains `ssl=true` or `sslmode=require`.
On reading Heroku's documentation (https://devcenter.heroku.com/articles/connecting-heroku-postgres) they acknowledge that, in production, applications almost always must specify these parameters but in their words 'You must add this parameter in code rather than editing the config var directly'.
As such, this is a partial revert but instead now wrap it with an environment check for production. This marries up to Heroku documentation.

Set Postgres TLS Configuration in Production

---

Public/css/style.css
Resources/Views/Home/_schedule.leaf

Currently markdown lists do not display accurately due to an over-zealous CSS rule. I've added a new class that allows us to scope styling just to these markdown fields.

Patch markdown lists styling

---

Public/.well-known/apple-app-site-association
Sources/App/Middleware/AppleAppSiteAssociationMiddleware.swift

disabled by default (returns a 404)
commenting out the middleware wouldn't work, just makes the file invalid which makes Apple grumpy.

add ability to disable/enable aasa

---

Resources/Views/Home/home.leaf
Sources/App/Context/HomeContext.swift
Sources/App/Features/Events/Models/Event.swift
Sources/App/Features/Schedule/ScheduleAPIController+V2.swift
Sources/App/Features/Slots/Transformers/SlotTransformer+V2.swift
Sources/App/Features/Sponsors/Controllers/SponsorAPIController.swift
Sources/App/routes.swift

This allows us to hide all speakers, sponsors, and presentations from a previous event from both the mobile app and the website simply by marking the event as "not current".
Merging this will cause the API to return empty arrays for the schedule and sponsors list (as there are non defined for this year yet).

Wire API and home screen to use 'isCurrent' event

---

Sources/App/Features/Schedule/Models/ScheduleResponse+V2.swift
Sources/App/Features/Schedule/ScheduleAPIController+V2.swift
Sources/App/Features/Schedule/Transformer/ScheduleTransformer+V2.swift

Add a new array of events with the schedule API call.  
This will be used within the App to enable linking to previous events.

Return all events with schedule API call

---

Sources/App/Features/Home/HomeRouteController.swift

https://twitter.com/___freddi___/status/1749473814734602514
Not sure what caused the Sessionize URL to change but it breaks the site 😅 
```
curl "https://sessionize.com/api/universal/event?slug=swiftleeds-ios-conference-in-leeds" \
-X GET \
-H "X-API-KEY: redacted"
```
Have tested this cURL command and it works - but not tested this PR (wrong laptop).

Update CFP URL

---

.github/workflows/build.yml
.github/workflows/close.yml

Only run GitHub actions if repo owner is `SwiftLeeds`.
This prevent workflow failures (as shown below) in forked repos.

Only run GitHub actions if repo owner is `SwiftLeeds`

---

Resources/Views/Dropin/slots.leaf
Sources/App/Features/DropIns/Controllers/DropInRouteController.swift
Sources/App/Features/DropIns/Controllers/DropInUserRouteController.swift
Sources/App/Features/DropIns/Models/DropInSession.swift
Sources/App/Features/DropIns/Models/DropInSessionSlot.swift
Sources/App/Features/DropIns/Models/Migrations/AddDropInGroupsMigration.swift
Sources/App/Features/DropIns/Models/Migrations/UseArrayDropInOwnerMigration.swift
Sources/App/Features/Events/Models/Event.swift
Sources/App/Features/Events/Models/Migrations/Event+Migration+V3.swift
Sources/App/Features/Tickets/Controllers/TicketLoginController.swift
Sources/App/Features/Tickets/Middleware/ValidTicketMiddleware.swift
Sources/App/Features/Tickets/Models/TitoTicket.swift
Sources/App/Features/Tickets/Services/TitoService.swift
Sources/App/Migrations.swift

* Adds support for users joining more than one drop-in session (exclusivity groups)
* Adds support for sessions with more than one participant (group sessions)
* Adds database support (no UI changes) for brand associated sessions (not sponsored)
* Adds support for database-driven tito ticket lookup (basically just means no code changes next year, but could mean multi-year support too and unlocks other features down the line)
* Fixes a bug introduced by Tito where unassigned tickets were being returned and breaking lookup
I have validated this locally for all variations.

Drop-in Sessions v2

---

Sources/App/Migrations.swift
Sources/App/configure.swift

Per [documentation](https://docs.vapor.codes/advanced/sessions/), sessions.use must be used before setting middleware. We had it flipped the wrong way.

Move Session Driver

---

.github/workflows/build.yml
.github/workflows/close.yml
Resources/Views/Hub/home.leaf
Sources/App/Features/Ticket Hub/Controllers/TicketHubRouteController.swift

Also untag artifacts on PR close, and configure images to auto-delete once untagged.
Looking at billing, this will be a 95% decrease in costs. Moving to GHCR would likely solve the rest, but seems insignificant so going to roll with this and review in a couple months.

Remove Secret Manager (Use GitHub Secrets)

---

Public/js/admin.js
Resources/Views/Admin/Form/activity_form.leaf
Resources/Views/Admin/Form/dropin_form.leaf
Resources/Views/Admin/Form/dropin_slot_form.leaf
Resources/Views/Admin/Form/dropin_slot_form_row.leaf
Resources/Views/Admin/Form/event_form.leaf
Resources/Views/Admin/Form/presentation_form.leaf
Resources/Views/Admin/Form/slot_form.leaf
Resources/Views/Admin/Form/sponsor_form.leaf
Resources/Views/Admin/dropins.leaf
Resources/Views/Admin/presentations.leaf
Resources/Views/Admin/speakers.leaf
Resources/Views/Admin/sync_modal.leaf
Sources/App/Features/DropIns/Controllers/DropInRouteController.swift
Sources/App/Features/DropIns/Models/DropInSession.swift
Sources/App/Features/DropIns/Models/Migrations/AddDropInTBAMigration.swift
Sources/App/Features/Events/Controllers/EventRouteController.swift
Sources/App/Features/Events/Models/Event.swift
Sources/App/Features/Events/Models/Migrations/Event+Migration+V4.swift
Sources/App/Features/Home/HomeRouteController.swift
Sources/App/Features/Presentations/Controllers/PresentationRouteController.swift
Sources/App/Features/Sessionize/Controllers/SessionizeSyncRouteController.swift
Sources/App/Features/Ticket Hub/Controllers/TicketHubRouteController.swift
Sources/App/Migrations.swift
Sources/App/routes.swift

- `isPublic` defaults to `false` meaning no presentation is shown until manually toggled
- This means when you create a slot, sponsor, etc, it will use the event you have in the filter in the sidebar
- You can move the entity to a different event if you edit the event afterwards
Not for this PR:

Admin Panel Extras

---

Sources/App/configure.swift

This was a bitch to debug, but looks like our sessions are being ignored only when routed through Firebase Hosting due to this little asterisks at the bottom of a docs page.
Can't test locally, but login and session storage does (continue to) work. Hopefully fixes production.

Replace Cookie Name

---

.github/workflows/build.yml

Brexit has reached SwiftLeeds! (No, it's unrelated).
We currently deploy into `europe-west1`, this is in London and gives the best possible speeds to our UK audience. However, this region does not support Google Cloud Run domain mapping. 
For this reason, we use Firebase Hosting as an additional layer on top of GCR. It does nothing but define a basic mapping between a custom domain and this service.
However this has caused us a few pain points over the time in which this has been deployed, notably:
1. It overrides your `apple-app-site-association` (fixed in https://github.com/SwiftLeeds/swiftleeds-web/commit/a949d14b3dd947d34224bdf6c0e15370faf30e36)
2. It tweaks how your cookies are stored (fixed in https://github.com/SwiftLeeds/swiftleeds-web/pull/135/commits/b9af785cb011c24654161057898c2 …

Move deployment to Belgium DC

---

Resources/Views/Admin/schedule.leaf
Resources/Views/Schedule/_schedule.leaf
Sources/App/Features/Event Day/Migrations/EventDay+Migration+V1.swift
Sources/App/Features/Slots/Controllers/SlotRouteController.swift
Sources/App/Features/Slots/Migrations/Slot+Migration+v3.swift
Sources/App/Features/Slots/Migrations/Slot+Migration+v4.swift
Sources/App/Features/Slots/Migrations/Slot+Migration+v6.swift
Sources/App/Features/Slots/Models/Slot.swift
Sources/App/Features/Slots/Transformers/SlotTransformer.swift
Sources/App/Migrations.swift
Sources/App/Tag/SessionEndTag.swift
Sources/App/routes.swift

Noticed during a fresh setup of this locally we had a few issues with migrations running related to deprecated properties on Slot. 
I've updated the migrations to be entirely work from a fresh install and (hopefully) work on existing deployments, and fixed the fully commented out migration with a fatalError in it to stop it running, hopefully all works _as expected_ now, famous last words, but all looks good from my side and I can create all things in my local Admin and see them on the website.
Note, this **does** break the seeder, I spent a bit of time trying to manually fix the SQL but I think I'll just replicate production manually by hand and then dump that SQL to get a fully correct version with 2024 and 2025's entries on as well anyways (but probably closer to the event to not leak …

 Slot property deprecations & migration fixes

---

Resources/Views/Home/_drop-in-sessions.leaf
Resources/Views/Hub/home.leaf
Sources/App/Context/HomeContext.swift
Sources/App/Features/Home/HomeRouteController.swift
Sources/App/Features/Ticket Hub/Controllers/TicketHubRouteController.swift
seed.sql

This PR is to try and enable better clarity on attendees being able to book BOTH an individual session vs. a group session.

Highlight Group Drop-In Sessions on the website
