Package.resolved
Package.swift
README.md
Resources/Views/home.leaf
Sources/App/configure.swift
Sources/App/routes.swift

This PR creates the foundation to add Leaf to the project to start building out the frontend pages.

Introduce Leaf for the frontend

---

Public/css/style.css
Resources/Views/Home/_about-us.leaf
Resources/Views/Home/_order-tickets.leaf
Resources/Views/Home/_previous-conferences.leaf
Resources/Views/Home/_speakers.leaf
Resources/Views/Home/_sponsors.leaf
Resources/Views/Home/home.leaf
Resources/Views/Shared/_footer.leaf
Resources/Views/Shared/_header.leaf

Creating anchor links for navigation bar + small improvements on look.

Anchor Links + Improvements

---

Public/css/style.css

Small change at the request of the designer 👨🏻‍🎨

Update the navigation bar to be slightly transparent on larger screens

---

Package.resolved
Package.swift
Resources/Views/Home/_speakers.leaf
Sources/App/Auth/Controllers/SpeakerController.swift

This Pull Request swaps out local storage for S3 upload

Adding S3 upload instead of using the local storage as Heroku shuts down

---

Resources/Views/Home/_previous-conferences.leaf
Resources/Views/base.leaf

This PR is adding Lightbox control to the images on the homepage.

Adding image zoom utilising LightBox

---

Resources/Views/Home/_location.leaf
Resources/Views/Home/home.leaf
Resources/Views/Shared/_header.leaf

This PR is to add a small map on the website to display the location of the venue. I figured it's best we do this given we're not actually displaying this.

Adding map for the location of the venue

---

Public/css/style.css
Resources/Views/Home/_schedule.leaf
Sources/App/routes.swift

We weren't previously loading speakers from the presentations model and now I have fixed that. I have introduced accordians to make it more in line with the designs.

Improve Schedule including Speaker Details

---

Resources/Views/Home/_location.leaf
Resources/Views/Home/_schedule.leaf
Resources/Views/Shared/_header.leaf

I am proposing we swap the navigation to include Speakers & Schedule, all the others can be discovered during the scrolling on the website.

Updating Navigation

---

Sources/App/Features/Activities/Controllers/ActivityAPIController.swift

Steals the approach @jw1540 used - I tried to combine them but somehow that didnt work 🤔

Fix activity image uploads

---

.env.development
Package.resolved
Package.swift
Sources/App/Features/Push/Controllers/PushController.swift
Sources/App/Features/Push/Migrations/PushMigration.swift
Sources/App/Features/Push/Models/Token.swift
Sources/App/Migrations.swift
Sources/App/configure.swift
Sources/App/routes.swift

APNS capability added to the project.  
New `/push` endpoint added to store user tokens.  
Test endpoint `/push/testNotification` added to allow testing for a specific token but only if generated on a Debug build.

Add Push capability and token storage

---

.env.development
Sources/App/Features/Push/Controllers/PushController.swift

Add endpoint to send Push notifications to all users using security code.

Allow notifications to be sent to all users

---

Resources/Views/Home/home.leaf
Resources/Views/Shared/_header.leaf
Resources/Views/Shared/_navigation.leaf
Sources/App/Context/HomeContext.swift
Sources/App/routes.swift

A couple tweaks now that 2022 is over, not a full sweep but enough not to send folks insane.

Remove Tickets Box

---

Resources/Views/Shared/_footer.leaf
Sources/App/Tag/CopyrightTag.swift
Sources/App/configure.swift

This PR will automatically set the current year through script vs. manually updating this each year.
I have also added the date the website went live.

Update Copyright Year Automatically

---

Resources/Views/Admin/sponsors.leaf
Sources/App/Features/Sponsors/Controllers/SponsorViewController.swift

Currently, we're unable to remove a sponsor through the admin dashboard. I have added new functionality to handle the removal of a sponsor directly through the admin dashboard.

Adding functionality to remove a sponsor from the admin dashboard.

---

Resources/Views/Dropin/list.leaf
Resources/Views/Dropin/slots.leaf
Resources/Views/Ticket/ticketLogin.leaf
Sources/App/Features/DropIns/Controllers/DropinRouteController.swift
Sources/App/Features/DropIns/Models/DropInSession.swift
Sources/App/Features/DropIns/Models/DropInSessionSlot.swift
Sources/App/Features/DropIns/Models/DropinUpdateModel.swift
Sources/App/Features/DropIns/Models/Migrations/AddDropInSessionMigration.swift
Sources/App/Features/DropIns/Models/Migrations/AddDropInSessionSlotsMigration.swift
Sources/App/Features/Events/Models/Event.swift
Sources/App/Features/Events/Models/Migrations/Event+Migration+V2.swift
Sources/App/Features/Schema.swift
Sources/App/Features/Tickets/Controllers/TicketLoginController.swift
Sources/App/Features/Tickets/Controllers/TicketsAPIController.swift
Sources/App/Features/Tickets/Middleware/ValidTicketMiddleware.swift
Sources/App/Features/Tickets/Models/TitoTicket.swift
Sources/App/Features/Tickets/Services/TitoService.swift
Sources/App/Migrations.swift
Sources/App/routes.swift
seed.sql

just refactoring things here and there
- contains db migrations
- admin work will come separately
- may tweak UI in future pr too
merge upon reviews

Couple small tweaks

---

Sources/App/Features/DropIns/Controllers/DropinRouteController.swift
Sources/App/Features/Sponsors/Controllers/SponsorViewController.swift
Sources/App/Features/Tickets/Controllers/TicketLoginController.swift

just addressing last build errors... difficult when it's only on deployment but should be good with this

add explicit returns

---

Resources/Views/Authentication/slot_form.leaf
Resources/Views/Shared/_header.leaf
Sources/App/Features/Events/Models/Event.swift
Sources/App/Features/Schedule/ScheduleAPIController+V2.swift
Sources/App/Features/Slots/Controllers/SlotAPIController.swift
Sources/App/Features/Slots/Migrations/Slot+Migration+v2.swift
Sources/App/Features/Slots/Models/Slot.swift
Sources/App/Features/Slots/Models/SlotResponse+V2.swift
Sources/App/Features/Slots/Transformers/SlotTransformer+V2.swift
Sources/App/Features/Sponsors/Controllers/SponsorAPIController.swift
Sources/App/Migrations.swift
seed.sql

* updated seeding, though given I've just changed it it's probably already out of sync
* allow for ?event=<uuid> on sponsors and schedule API (to override current)
* add full date+time to schedule response (not just HH:mm) - this will be a gradual transition to support backwards compatibility
* fixes a bug in Adams last PR 🙄 😉 
* admin tweaks to support new date format in slots
this should unblock mobile, with exception to new events API (though this is not **required**)

Misc Changes

---

Resources/Views/Authentication/create_events.leaf
Resources/Views/Authentication/sponsor_form.leaf
Sources/App/Features/LastUpdated/Model/LastUpdated.swift
Sources/App/Features/LastUpdated/Model/Migrations/LastUpdatedMigrationV1.swift
Sources/App/Features/Schema.swift
Sources/App/Features/Sponsors/Controllers/SponsorAPIController.swift
Sources/App/Features/Sponsors/Models/Middleware/SponsorMiddleware.swift
Sources/App/Features/Sponsors/Models/Migrations/SponsorMigrationV2.swift
Sources/App/Features/Sponsors/Models/Sponsor.swift
Sources/App/Features/Sponsors/Models/SponsorResponse.swift
Sources/App/Features/Sponsors/Transformers/SponsorTransformer.swift
Sources/App/Migrations.swift
Sources/App/configure.swift

Resolved some issues with Sponsor UI and added new 'subtitle' field.  
Added new optional 'subtitle' field to API.  
Added new table to handle model updates to use for eTags.

Add subtitle to sponsor and eTag to API

---

Resources/Views/Admin/Form/slot_form.leaf
Resources/Views/Admin/home.leaf
Resources/Views/Admin/sponsors.leaf

Added Event filtering to Sponsors list.  
Added filtering on Slot screen for Activities and Presentations so only those matching the selected Event will be enabled.

Add filtering to Slot values and Sponsors

---

Resources/Views/Home/_schedule.leaf
Resources/Views/Home/home.leaf
Sources/App/Context/HomeContext.swift
Sources/App/Features/Slots/Models/Slot.swift
Sources/App/routes.swift

Added a function to split the slots into separate days, and add headers for that day (if more than 1 day)

Split slots into multiple days for front-end

---

.github/workflows/build.yml
Package.resolved
Resources/Views/Home/_hero.leaf
Resources/Views/Home/_info.leaf
Resources/Views/Home/_ticket_cta.leaf

Supa Trouper

---

Resources/Views/Hub/_carousel.leaf
Sources/App/Features/DropIns/Models/DropInSessionSlot.swift
Sources/App/Features/DropIns/Models/Migrations/AddDurationToDropInMigration.swift
Sources/App/Features/Ticket Hub/Controllers/TicketHubRouteController.swift
Sources/App/Migrations.swift

New modals too:
Notably, this adds duration to slots. This means a single session can have slots of varying lengths. Not sure if/when we'd want to do this - but could add some variety.

Add Duration to Drop In Sessions

---

Public/css/theme.css
Resources/Views/Home/_speakers.leaf
Resources/Views/Home/_sponsors.leaf
Sources/App/Features/Activities/Models/Activity.swift
Sources/App/Features/Auth/Models/User.swift
Sources/App/Features/Auth/Models/UserToken.swift
Sources/App/Features/DropIns/Controllers/DropInRouteController.swift
Sources/App/Features/DropIns/Models/DropInSession.swift
Sources/App/Features/DropIns/Models/DropInSessionSlot.swift
Sources/App/Features/Events/Models/Event.swift
Sources/App/Features/Jobs/Model/Job.swift
Sources/App/Features/LastUpdated/Model/LastUpdated.swift
Sources/App/Features/Location Categories/Model/LocationCategory.swift
Sources/App/Features/Locations/Model/Location.swift
Sources/App/Features/Presentations/Models/Presentation.swift
Sources/App/Features/Push/Models/Token.swift
Sources/App/Features/Sessionize/Controllers/SessionizeSyncRouteController.swift
Sources/App/Features/Slots/Models/Slot.swift
Sources/App/Features/Speakers/Models/Speaker.swift
Sources/App/Features/Sponsors/Controllers/SponsorAPIController.swift
Sources/App/Features/Sponsors/Models/Sponsor.swift

* Update font usage
* Give sponsors more space (use two lines so they're bigger, esp when we add more)
* Fix all codebase warnings (except the SPM ones which we can't fix as documented)
* Minor tweak where pluralisation is off when we only have one announcement

Minor Tweaks for Homepage

---

.github/workflows/build.yml
Resources/Views/Admin/Form/speaker_form.leaf
Resources/Views/Admin/speakers.leaf
Resources/Views/Home/_speakers.leaf
Resources/Views/Shared/_header.leaf
Resources/Views/Ticket/ticketLogin.leaf
Sources/App/Features/DropIns/Controllers/DropInRouteController.swift
Sources/App/Features/Home/HomeRouteController.swift
Sources/App/Features/Sessionize/Controllers/SessionizeSyncRouteController.swift
Sources/App/Features/Speakers/Controllers/SpeakerRouteController.swift
Sources/App/Features/Speakers/Models/Migrations/Speaker+Migration+V2.swift
Sources/App/Features/Speakers/Models/Speaker.swift
Sources/App/Features/Tickets/Controllers/TicketLoginController.swift
Sources/App/Migrations.swift
Sources/App/routes.swift

Read through the commit titles for a changelog - all quick wins and bug fixes.

Quick Wins

---

Resources/Views/Home/year/hero-2025.leaf

Tweak countdown prefix

---

Resources/Views/CFP/_cfp.leaf

This is not complete, pushing it up to get help.

Add CFP Suggestions
